# Exercise 1.A NumPy: Manipulating Arrays

In [2]:
import numpy as np

## Looping Through Arrays

In [3]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [4]:
arrA =np.array([
    [11, 12, 13],
    [14, 15, 16]
])

for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The difference between the output of the first loop and second is that the first loop gives back each row doubled while the second loop gives back the numbers indivisually from looping through each element inside the row.

In [6]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)
# The result is different because we are looping through each element, but the calculation is done
# through each row instead. So now it will print the same row result instead of changing with each
# element(number).

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [16]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

# axis=0 means you join row by row (vertical stacking), so you get the same array placed 
# underneath itself.

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [17]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [18]:
stacked_array_1 = np.concatenate((joined_array_1, joined_array_1))
print(stacked_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [19]:
stacked_array_2 = np.concatenate((joined_array_1, joined_array_2))
print(stacked_array_2)
# The error message I get is a ValueError. All arrays must match except for the concatenation.
# Array 1 has 3 columns while Array 2 has 6 columns.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 6

In [31]:
another_joined_array = np.concatenate ((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [34]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
# When you run this code, it will give you a ValueError.
# To put it in my own words, it is because they do not have the same number of rows. 
# joined_array has 4 rows while arrA has 2 rows, so they can't be joined on axis=1.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [41]:
Vari1 = np.hstack((arrA, arrA))
# This is a horizantal stack. As in the name it makes the stack horizantal by adding them 
# side-by-side.
Vari2 = np.vstack((arrA, arrA))
# This is a vertical stack. It makes the stacks vertical by adding rows onn top of each other.
Vari3 = np.dstack((arrA, arrA))
# This is a depth stack. It stacks the array along a third deminsional.

print(Vari1)
print()

print(Vari2)
print()

print(Vari3)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [43]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)
# This returns a list with 2 seperate arrays. Using still the same dimension which is 
# 2-dimension with 2 columns and 3 rows.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [45]:
spliterino = np.split(joined_array_1, 3)
print(spliterino)
# This will give an error because the array has on four rows and can't evenly be split into
# three. 

ValueError: array split does not result in an equal division

## Searching and Replacing Array Values

In [46]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [48]:
arrB = np.array([
    [7,6],
    [13, 5],
    [7, 3]
])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [51]:
print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [52]:
print(arrB)

y = arrB >= 7
arrD = arrB[y]

print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
