# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])
print(arrA)

[[11, 12, 13], [14, 15, 16]]


In [5]:
arrA =np.array([
    [11, 12, 13],
    [14, 15, 16]
])

for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [10]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The difference between the output of the first loop and second is that the first loop gives back each row doubled while the second loop gives back the numbers indivisually from looping through each element inside the row.

In [13]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)
# The result is different because we are looping through each element, but the calculation is done
# through each row instead. So now it will print the same row result instead of changing with each
# element(number).

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [17]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

# axis=0 means you join row by row (vertical stacking), so you get the same array placed 
# underneath itself.

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [21]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [ ]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
stacked_array_1 = np.concatenate((joined_array_1, joined_array_1))
print(stacked_array_1)