# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [3]:
r_1 = np.random.randint(1,21, size=2)
print(r_1)

[13 13]


In [5]:
r_2 = np.random.randint(1,21, size=(1,2))
print(r_2)

[[13 13]]


In [7]:
r_3 = np.random.random(size=(2,1))
print(r_3)

[[0.18813567]
 [0.67508761]]


In [10]:
r_4 = np.random.randint(20,101, size=(4,5))
print(r_4)

[[ 98  96  91  38  65]
 [100  47  65  69  52]
 [ 79  60  77  56  69]
 [ 53  96  61  94  83]]


In [11]:
r_5 = np.random.random(size=(4,5))
print(r_5)

[[0.48105321 0.13770747 0.97894755 0.04474604 0.82639457]
 [0.17822948 0.70431814 0.87399293 0.79627119 0.03640893]
 [0.69561487 0.7563948  0.69851761 0.92846178 0.12258707]
 [0.8633255  0.60801443 0.86489989 0.77494136 0.70132499]]


## Generating Random Choices from an Array

In [13]:
students = np.array([ 
    "Sharleen", "Vesna", "Jordan", "Leon", 
    "Lilly", "Demy", "Yanuris", "Malaika", 
    "Kasaiha", "Jonathan", "Marenza", "Dania"
])

In [14]:
call_on = np.random.choice(students)
print(call_on)

Yanuris


In [17]:
breakout_groups = np.random.choice(students, size=(3,4))
print(breakout_groups)
# This can be used to assign breakout rooms, but it's not ideal because students can be 
# chosen twice or not at all. It may be random, but random can also give duplicates of
# one value.

[['Leon' 'Jonathan' 'Vesna' 'Malaika']
 ['Sharleen' 'Leon' 'Leon' 'Dania']
 ['Yanuris' 'Yanuris' 'Marenza' 'Lilly']]


In [19]:
p_values = [0.30, 0.15, 0.10, 0.10,
            0.08, 0.07, 0.05, 0.05,
            0.04, 0.03, 0.03, 0.00]
# Probability values for each student:
# Sharleen = 30% chance
# Vrsna = 15% chance
# Jordan = 10% chance
# Leon = 10% chance
# Lilly = 8% chance
# Demy = 7% chance
# Yanuris = 5% chance
# Malaika = 5% chance
# Kasaiha = 4% chance
# Jonathan = 3% chance
# Marenza = 3% chance
# Dania = 0% chance (will never be selected)

call_on_weighted = np.random.choice(students, size=5, p=p_values)
print(call_on_weighted)

['Marenza' 'Sharleen' 'Lilly' 'Demy' 'Leon']


## Generating a Normal Distribution

In [21]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 9.41094428  8.17437035  9.01158604  9.97792046  0.15452278]
 [ 8.34792363 12.00195355 13.73100916  5.01563092  6.15326898]
 [10.45898681  7.63692159 12.84636192  3.54035819 17.39131788]
 [ 0.21587348 13.06169855  9.71693606 14.62555705 16.05363599]]
