# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [4]:
r_1 = np.random.randint(1,21, size=2)
r_2 = np.random.randint(1,21, size=(1,2))
r_3 = np.random.random(size=(1,2))
r_4 = np.random.randint(20,101, size=(4,5))
r_5 = np.random.random(size=(4,5))

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[ 4 18]
[[ 6 17]]
[[0.15963179 0.50047153]]
[[ 38  44  28  60  68]
 [ 40 100  57  87  71]
 [ 79  74  79  38  75]
 [ 93  65  27  44  49]]
[[0.14685153 0.04051128 0.4023059  0.82124264 0.10307532]
 [0.53957414 0.25367701 0.14191298 0.97388924 0.541251  ]
 [0.55772477 0.47261039 0.25259558 0.10453774 0.18197741]
 [0.44893164 0.15281074 0.01955745 0.95047013 0.67911583]]


## Permutations

In [6]:
print("Original r_4:")
print(r_4)

np.random.shuffle(r_4)

print("\nShuffled r_4:")
print(r_4)

Original r_4:
[[ 79  74  79  38  75]
 [ 93  65  27  44  49]
 [ 38  44  28  60  68]
 [ 40 100  57  87  71]]

Shuffled r_4:
[[ 93  65  27  44  49]
 [ 79  74  79  38  75]
 [ 38  44  28  60  68]
 [ 40 100  57  87  71]]


In [7]:
# After using random shuffle, the rows are shuffled in place. It only rearranges the 
# order of the rows but not the elements inside them.

In [10]:
new_shuffle = np.random.permutation(r_4)
print("new shuffle:")
print(new_shuffle)

print("\nr_4 (original after permutation):")
print(r_4)

new shuffle:
[[ 93  65  27  44  49]
 [ 40 100  57  87  71]
 [ 38  44  28  60  68]
 [ 79  74  79  38  75]]

r_4 (original after permutation):
[[ 93  65  27  44  49]
 [ 79  74  79  38  75]
 [ 38  44  28  60  68]
 [ 40 100  57  87  71]]


You know when to use them, depending on whether you want to change the original data or keep it unchanged. 